{
 "title": "Real Time Twitter Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Twitter Analytics",
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n<img height=\"100px\" src=\"http://wpafirenews.com/wp2/wp-content/uploads/2017/03/twitter-logo.png\" />\n<img height=\"100px\" src=\"https://bprd.nic.in/images/logo.png\" />\n</center>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Hashtag Counts",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT hashtag as \"Hashtags\", count(*) as \"Tweet Count\" FROM `hashtags` GROUP BY hashtag order by count(*) DESC"
    }
   ]
  },
  {
   "title": "World Heatmap",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select count(id) as \"Tweet Count\", latitude, longitude from tweets group by latitude, longitude order by count(id) desc limit 40"
    }
   ]
  },
  {
   "title": "Real Time Tweet Analysis",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  id as \"Tweet ID\", timestamp as \"Time Stamp\", user_name as \"User Name\", text as \"Content\", location as \"Location\", text_polarity as \"Text Toxicity (%)\"\nFROM tweets\nORDER BY timestamp DESC\n"
    }
   ]
  }
 ]
}